version: '2'

services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - ${APACHE_PORT:-127.0.0.1:8000}:80
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_TEST_DB: '${POSTGRES_TEST_DB}'
    ports:
      - ${POSTGRES_PORT:-127.0.0.1:5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/pgsql/init-testing-db.sh:/docker-entrypoint-initdb.d/init-testing-db.sh
    healthcheck:
      test: /usr/bin/pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 1s
      start_period: 5s

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
       # SWAGGER_JSON_URL: ${SWAGGER_UI_URL}
       URL: ${SWAGGER_UI_URL}
       # URLS: "[
       #   { url: 'https://petstore.swagger.io/v2/swagger.json', name: 'Petstore' }
       # ]"
    ports:
      - "127.0.0.1:81:8080"

volumes:
  pgdata:
    driver: local
